// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6sN7k0wsar9dHLdfDRjtg6Q4LyvWcirw',
    appId: '1:851114143104:web:a791d7c5502d183eefa565',
    messagingSenderId: '851114143104',
    projectId: 'your-stock-project',
    authDomain: 'your-stock-project.firebaseapp.com',
    storageBucket: 'your-stock-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-oZujYTH0Wl1D225TX35YvjzRfllQgfU',
    appId: '1:851114143104:android:f07d4b615602c4daefa565',
    messagingSenderId: '851114143104',
    projectId: 'your-stock-project',
    storageBucket: 'your-stock-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyRfebOGV0dsKLUhuznk8_V8qTmxSgXaI',
    appId: '1:851114143104:ios:fb430ecacc146cfdefa565',
    messagingSenderId: '851114143104',
    projectId: 'your-stock-project',
    storageBucket: 'your-stock-project.appspot.com',
    iosClientId: '851114143104-jio2n74dbcsaangmee42ti5okqf7gg33.apps.googleusercontent.com',
    iosBundleId: 'eg.Almoghair.yourstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyRfebOGV0dsKLUhuznk8_V8qTmxSgXaI',
    appId: '1:851114143104:ios:fb430ecacc146cfdefa565',
    messagingSenderId: '851114143104',
    projectId: 'your-stock-project',
    storageBucket: 'your-stock-project.appspot.com',
    iosClientId: '851114143104-jio2n74dbcsaangmee42ti5okqf7gg33.apps.googleusercontent.com',
    iosBundleId: 'eg.Almoghair.yourstock',
  );
}
